fieldLayouts:
  01afbf32-7231-46a1-9f91-1973689d81f7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-08T21:08:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: f3ccf97b-4996-4b20-b9d6-36a48a888f49
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4089a4ed-d9bc-4fe0-8b65-51b2a3fe04c7
        userCondition: null
handle: episodes
name: Episodes
