tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2025-01-08T16:09:49-05:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: 39bed594-5a11-4fdb-aa55-84735bcd46cc
        userCondition: null
        warning: null
        width: 100
      -
        attribute: countryCode
        dateAdded: '2025-01-08T16:09:49-05:00'
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: 1d43cd55-593f-4558-af9f-4f486d735fa2
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2025-01-08T16:09:49-05:00'
        elementCondition: null
        includeInCards: true
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: 83b9fcde-2702-4104-a02b-155073090299
        userCondition: null
        warning: null
    name: Content
    uid: 0e1bf798-47f3-4ad9-90ce-beb3b1aae012
    userCondition: null
