tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2025-02-01T23:44:18-05:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: ff1c7b12-cc1d-486f-93cd-1db1aa279cc9
        userCondition: null
        warning: null
        width: 100
      -
        attribute: countryCode
        dateAdded: '2025-02-01T23:44:18-05:00'
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: ba67fc63-260b-487e-8abd-e725923446d2
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2025-02-01T23:44:18-05:00'
        elementCondition: null
        includeInCards: true
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: 70757f73-cc3e-42b9-a306-ae1c3a1b75e4
        userCondition: null
        warning: null
    name: Content
    uid: 5a213c1a-bc57-4607-bb12-9a92f61d5ed0
    userCondition: null
