altTranslationKeyFormat: null
altTranslationMethod: site
fieldLayouts:
  3eb40d2e-5571-4c14-a5df-2a714e403859:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-02T04:38:03+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 71011448-5b56-4440-9f84-b3c21070895e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3d04041a-2f11-4290-b572-72d21c4a0308
        userCondition: null
fs: devmodeTranscripts
handle: devmodeTranscripts
name: 'Devmode Transcripts'
sortOrder: 7
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
