tabs:
  -
    elementCondition: null
    elements:
      -
        attribute: fullName
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2025-02-02T04:38:03+00:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: true
        required: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\users\FullNameField
        uid: a86ac2e5-070d-4399-a33d-cd933e6a0a54
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2025-02-02T04:38:03+00:00'
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\users\PhotoField
        uid: 79315b9b-322f-4224-be2e-0aecb0bd79c9
        userCondition: null
        warning: null
        width: 100
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2025-02-02T04:38:03+00:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\users\EmailField
        uid: 627896f7-3e17-4dbe-80cb-b4d3743976c1
        userCondition: null
        width: 100
      -
        dateAdded: '2025-02-02T04:38:03+00:00'
        elementCondition: null
        fieldUid: c05161c0-a294-4d47-8909-1cfc88c2f970 # Profile Company
        handle: null
        includeInCards: false
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: c1a2f673-fec8-4c49-b4d1-c418351565f7
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2025-02-02T04:38:03+00:00'
        elementCondition: null
        fieldUid: 380e3b7e-07de-4d39-b0e5-360f5e87d00d # Profile Title
        handle: null
        includeInCards: false
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 64d5f3f1-35c8-426c-9572-ffa129bee863
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2025-02-02T04:38:03+00:00'
        elementCondition: null
        fieldUid: 9687721c-33b8-4a40-abb7-5c42e07ce274 # Profile Bio
        handle: null
        includeInCards: false
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 53c91a02-f5cb-4d3e-92ca-c90d91b235fc
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2025-02-02T04:38:03+00:00'
        elementCondition: null
        fieldUid: 31b8c511-37f9-4d83-956d-5aa215572122 # Profile URL
        handle: null
        includeInCards: false
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 7834455e-565b-4397-b2a8-572b83ad3020
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2025-02-02T04:38:03+00:00'
        elementCondition: null
        fieldUid: 406c20cb-9b86-4b0d-9123-1ce57220e2a8 # Profile Twitter URL
        handle: null
        includeInCards: false
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 8a93a1a5-1ba9-40f9-9b94-f2332c96ad45
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2025-02-02T04:38:03+00:00'
        elementCondition: null
        fieldUid: d6df6fe7-14f3-42a3-9949-dcee7c8c26d9 # Profile GitHub URL
        handle: null
        includeInCards: false
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 6ca34656-fa0f-4762-a507-40e43e22fba3
        userCondition: null
        warning: null
        width: 100
    name: Profile
    uid: 5aa0e98d-2f2b-4800-8f9e-a8f051de8abd
    userCondition: null
