defaultPlacement: end
enableVersioning: false
entryTypes:
  - cc4ea2bd-3bde-4bad-8f72-272fcc3c2a19 # About
handle: about
maxAuthors: 1
name: About
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  2a4761bd-2461-4db9-96a0-4f52b8cef633: # devMode
    enabledByDefault: true
    hasUrls: true
    template: about/index
    uriFormat: about
type: single
