defaultPlacement: end
enableVersioning: false
entryTypes:
  - 7f6ad724-41b7-4a93-bef9-7de87d1bb23e # Calendar
handle: calendar
maxAuthors: 1
name: Calendar
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  2a4761bd-2461-4db9-96a0-4f52b8cef633: # devMode
    enabledByDefault: true
    hasUrls: true
    template: calendar/index
    uriFormat: calendar
type: single
