defaultPlacement: end
enableVersioning: false
entryTypes:
  - 50012289-791c-48b2-8df1-31a8f5eb5380 # Episodes Index
handle: episodesIndex
maxAuthors: 1
name: 'Episodes Index'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  2a4761bd-2461-4db9-96a0-4f52b8cef633: # devMode
    enabledByDefault: true
    hasUrls: true
    template: episodes/index
    uriFormat: episodes
type: single
