defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 032dc0eb-27cf-4034-ad36-dc8c274a455e # Guests
handle: guests
maxAuthors: 1
name: Guests
propagationMethod: all
siteSettings:
  2a4761bd-2461-4db9-96a0-4f52b8cef633: # devMode
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
