defaultPlacement: end
enableVersioning: false
entryTypes:
  -
    uid: 9aae2c4b-7316-4ee9-a2d1-41474766b361 # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  2a4761bd-2461-4db9-96a0-4f52b8cef633: # devMode
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
