defaultPlacement: end
enableVersioning: false
entryTypes:
  - 78ad1f1e-5dc5-4cff-b19f-43aa4ec02869 # 404 Not Found
handle: notFound
maxAuthors: 1
name: '404 Not Found'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  2a4761bd-2461-4db9-96a0-4f52b8cef633: # devMode
    enabledByDefault: true
    hasUrls: true
    template: 404.twig
    uriFormat: '404'
type: single
