columnSuffix: null
handle: episodeReferenceLinks
instructions: null
name: 'Episode Reference Links'
searchable: true
settings:
  addRowLabel: 'Add a row'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'Link Name'
            -
              - handle
              - linkName
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - 'Link URL'
            -
              - handle
              - linkUrl
            -
              - width
              - ''
            -
              - type
              - singleline
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
