columnSuffix: null
handle: episodeTags
instructions: null
name: 'Episode Tags'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: true
  source: 'taggroup:fc24a736-c435-4d8a-aeb3-6105afce1d91' # Episodes
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Tags
