columnSuffix: null
handle: episodeNumber
instructions: null
name: 'Episode Number'
searchable: true
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 1
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: 10
  step: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
