columnSuffix: null
handle: showUrl
instructions: null
name: 'Show URL'
searchable: true
settings:
  fullGraphqlData: false
  maxLength: 255
  showLabelField: false
  types:
    - entry
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
