columnSuffix: null
handle: showRssFeedUrl
instructions: null
name: 'Show RSS Feed URL'
searchable: true
settings:
  maxLength: 255
  showLabelField: false
  showTargetField: false
  types:
    - entry
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
