columnSuffix: null
handle: showDescription
instructions: null
name: 'Show Description'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 6
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
