color: null
fieldLayouts:
  9edff6e0-a6a2-48af-bf47-46bcf0704960:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-08T21:08:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c069761f-2823-4657-b2b2-ce0b7e896bbd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f1c94c2b-be68-49aa-9a41-278431d971e8
        userCondition: null
handle: calendar
hasTitleField: true
icon: null
name: Calendar
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
