color: null
fieldLayouts:
  871fe128-2837-48cb-a9ac-29f46ae27488:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-08T21:08:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d57f6696-fe10-4cb3-936d-4619d794c531
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 90f85740-1500-4535-94f5-e7e3507dbf38
        userCondition: null
handle: episodesIndex
hasTitleField: false
icon: null
name: 'Episodes Index'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
