color: null
fieldLayouts:
  87e65db2-3d89-4271-a91e-f06dc48b7a01:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-08T21:08:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2ac10f4c-0657-4be9-aee0-99a6e5c17d2e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-08T21:08:40+00:00'
            elementCondition: null
            fieldUid: 18d7721b-780b-4a44-976a-716c3df0bb7a # Error Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3f00ad4-e7dd-4ad5-a1aa-ad803b37377c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-08T21:08:40+00:00'
            elementCondition: null
            fieldUid: e1087165-5769-428d-bf14-c98e6011cf5e # Error Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 210c6725-6115-4c25-93d7-5ac2a67797e5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-08T21:08:40+00:00'
            elementCondition: null
            fieldUid: 4d90d0e7-b705-4035-b396-2f82ce5bb871 # Error Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6fc0279e-4ea3-4cad-be25-310d5e08c8a6
            userCondition: null
            warning: null
            width: 100
        name: Errors
        uid: a3c3c106-1389-46a0-9d60-668000ced1e8
        userCondition: null
handle: siteOffline
hasTitleField: true
icon: null
name: 'Site Offline'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: ''
